#!/bin/sh

# ./validate <meta data file path> <schema file path>
###################################################################################################################################################

java -Xmx2048M -jar meta-data-validator.jar $1 $2
