#!/bin/sh

# ./validate <meta data file path> <schema file path>
###################################################################################################################################################

java -Xmx2048M -jar target/meta-data-validator.jar $@
